spring:
  application:
    name: marsmall
  config:
    import:
      - optional:classpath:/secret/config.yml
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    open-in-view: false
    properties:
      jakarta.persistence.sharedCache.mode: UNSPECIFIED # default
      hibernate:
        format_sql: true

---
spring.config.activate.on-profile: dev

spring:
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type.descriptor.sql.BasicBinder: trace
        engine:
          transaction:
            internal:
              TransactionImpl: DEBUG
      springframework:
        transaction: DEBUG

---
spring.config.activate.on-profile: prod

spring:
  jpa:
    hibernate:
      ddl-auto: none
