on:
  push:
    branches:
      - main

env:
  APP_NAME: marsmall
  AWS_REGION: ap-northeast-2
  AWS_S3_BUCKET: mars-deploy-githubaction
  AWS_S3_BUCKEY_KEY: marsmall.zip

jobs:
  build:
    runs-on: ubuntu-22.04

    defaults:
      run:
        working-directory: ${{ env.APP_NAME }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Execute gradle build
        run: |
          chmod +x gradlew
          ./gradlew build --no-daemon -x test

      - name: Copy deploy files and zip
        run: |
          cp ./build/libs/$APP_NAME-0.0.1-SNAPSHOT.jar ./deploy
          zip -r -qq ./$AWS_S3_BUCKEY_KEY ./deploy

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      
      - name: Deliver to AWS S3
        run: aws s3 cp --acl private ./$AWS_S3_BUCKEY_KEY s3://$AWS_S3_BUCKET/
      
      - name: AWS CodeDeploy
        run: |
          aws deploy create-deployment \
          --application-name mars-codedeploy \
          --deployment-group-name mars-githubaction-s3-codedeploy \
          --s3-location bucket=$AWS_S3_BUCKET,bundleType=zip,key=$AWS_S3_BUCKEY_KEY
